### ISSUE TITLE
teacher/asset/add "DeserializationError"

### ISSUE THREAD

**Issue by kokeroulis** [kokeroulis/modip#7]
When i am trying to make a post request into the teacher/asset/add
I get the following error:

{
classification: "DeserializationError"
message: "json: cannot unmarshal string into Go value of type int"
}

You can reproduce this one from the UI.
On TeacherService.addAsset you must put console.log(result) into the then callback,
in order to see the error.

**Comment by gtsiap** [comment]
So, you are using the addAsset function from TeacherService but you come across to this error. Right?

Are you sure that the parameters type of addAsset are correct? 
Can you check if like `console.log(typeof foo);?`

**Comment by kokeroulis** [comment]
> So, you are using the addAsset function from TeacherService but you come across to this error. Right?

yes. This is the object which i am sending to the server...

{content: "adsdsadsa", assettype: "1"} 

Also the route teacher/info, returns nothing on the "assets", 
but when i look into the db, there is the default entry, "Super Book"...

Can u reproduce both of these issues?

**Comment by gtsiap** [comment]
`{content: "adsdsadsa", assettype: "1"}`

assettype is a _STRING_ it should be _INT_ like,

`{content: "adsdsadsa", assettype: 1}`

**Comment by kokeroulis** [comment]
So everytime we must cast explicitly a string into to int??
Wouldn't it be better if we allow both of them and shutting them down when they reach the go?

for example

type Asset struct {
    Content string `json:"string"`
    AssetId int `json:",string,int"`
}

I think that with the above we can accomplish something like the following:

AssetId gets a string from json, it tries to convert it, into an int, if it success it continues otherwise
it fails... Is that possible?

**Comment by gtsiap** [comment]
> I think that with the above

Its not possible technically.

> So everytime we must cast explicitly a string into to int??

I would prefer if the controllers where able to pass the data using the
correct types. The rest of the solutions would be very ugly.

**Comment by kokeroulis** [comment]
I am closing this one and mark it as solved.
The solution to the above problem is to do convert our string into to an int from the javascript.
In order to do that we can use the build in function parseInt.
